# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
# from sphinx.util.tags import  Tags
# import  sphinx.builders.Builder

# -- Project information -----------------------------------------------------

project = 'glm'
copyright = '2019, zhangzhenhu. acmtiger@outlook.com'
author = '张振虎'

# The short X.Y version
version = '0.1'
# The full version, including alpha/beta/rc tags
release = '草稿'

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    # 'sphinx.ext.imgmath',
    'sphinx.ext.mathjax',
    'sphinx.ext.githubpages',
    'sphinx.ext.todo',
    # 'sphinxcontrib.video',
    # 'sphinxcontrib.proof',
    'sphinxcontrib.tikz',
    'sphinx.ext.githubpages',
    'sphinx.ext.autosectionlabel',
    # 'sphinx.ext.todo',
    # 'recommonmark',
    'sphinxcontrib.bibtex',
    'sphinx_rtd_theme',
]
todo_include_todos = True
tikz_proc_suite = 'pdf2svg'
# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = []
# source_suffix = {'.rst': 'restructuredtext',
#                  '.md': 'markdown',
#                  }
# print(tags.tags)
# print(tags.has("html"))
exclude_patterns = [
    "参数估计/other.rst",
    "广义线性模型/draft.rst",
    "高斯模型/draft.rst",
    "import.rst",
    "广义线性模型/estimate_bak.rst",
    "常见分布/poisson.rst",
    "泊松模型/poisson.rst",
    "常见分布/content.rst",
]
if tags.has("html"):

    master_doc = 'index'
    # The master toctree document.
    exclude_patterns.extend([

    ])
else:
    # master_doc = 'probability_model/index_pdf/index'
    master_doc = 'index'
    exclude_patterns.extend([
        "important.rst",

    ])
# exclude_patterns = []

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
# exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# bibtex_bibfiles = ['参考文献/references.bib']

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# mathjax_path = "MathJax/latest.js?config=TeX-AMS-MML_HTMLorMML"
# mathjax_path = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js'
# mathjax_path = "/book/build/_static/MathJax/es5//latest.js?""config=TeX-AMS-MML_HTMLorMML"
import statsmodels

# html_theme = 'alabaster'
# ---sphinx-themes-----
# html_theme = 'p-green'
html_theme = 'sphinx_rtd_theme'
# html_theme = 'scikit-learn-modern'
# html_theme_options = {'google_analytics': False,
#                       'mathjax_path': mathjax_path}
# html_theme_path = ['themes']
import os

# from PSphinxTheme import utils

# p, html_theme, needs_sphinx = utils.set_psphinxtheme(html_theme)
# html_theme_path = p

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}
html_theme_options = {
    # 'canonical_url': '',
    # 'analytics_id': 'UA-XXXXXXX-1',  #  Provided by Google in your dashboard
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    # 'vcs_pageview_mode': '',
    # 'style_nav_header_background': 'white',
    # Toc options
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = [
    # '_static',
]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {
#     '**': [
#         'about.html',
#         'navigation.html',
#         'relations.html',  # needs 'show_related': True theme option to display
#         'searchbox.html',
#         # 'donate.html',
#     ]
# }
todo_include_todos = True

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'learningbookdoc'

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # 'papersize' : 'a4paper',
    'utf8extra': '',
    'inputenc': '',
    'babel': r'''\usepackage[english]{babel}''',
    'preamble': r'''
\usepackage{ctex}
\setmainfont{Source Serif Pro}
\setsansfont{Source Sans Pro}
\setmonofont{Source Code Pro}
\setCJKmainfont[BoldFont=Source Han Serif SC SemiBold]{Source Han Serif SC}
\setCJKsansfont[BoldFont=Source Han Sans SC Medium]{Source Han Sans SC Normal}
\setCJKmonofont{Source Han Sans SC Normal}
\addto\captionsenglish{\renewcommand{\chaptername}{}}
\addto\captionsenglish{\renewcommand{\contentsname}{目录}}
\usepackage[draft]{minted}
\fvset{breaklines=true, breakanywhere=true}
\setlength{\headheight}{13.6pt}
\makeatletter
    \fancypagestyle{normal}{
        \fancyhf{}
        \fancyfoot[LE,RO]{{\py@HeaderFamily\thepage}}
        \fancyfoot[LO]{{\py@HeaderFamily\nouppercase{\rightmark}}}
        \fancyfoot[RE]{{\py@HeaderFamily\nouppercase{\leftmark}}}
        \fancyhead[LE,RO]{{\py@HeaderFamily }}
     }
\makeatother
\CJKsetecglue{}
\usepackage{zhnumber}
''',
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',

    # Latex figure (float) alignment
    # 'figure_align': 'htbp',
    'figure_align': 'H',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'glm.tex', 'glm Documentation',
     'zzh', 'manual'),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'glm', 'glm Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'glm', 'glm Documentation',
     author, 'glm', 'One line description of project.',
     'Miscellaneous'),
]

# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

# -- Extension configuration -------------------------------------------------
mathjax_path = "MathJax/latest.js?config=TeX-AMS-MML_HTMLorMML"
# mathjax_path = ('https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js')
# mathjax_path = "/book/build/_static/MathJax/es5//latest.js?""config=TeX-AMS-MML_HTMLorMML"

mathjax_config = {
    "TeX": {
        "Macros": {
            "RR": '{\\bf R}',
            "bold": ['{\\bf #1}', 1]
        }
    }
}

# -- Options for pdf output -------------------------------------------------
# 配置项说明
# https://www.sphinx-doc.org/en/master/usage/configuration.html#latex-options
# https://www.sphinx-doc.org/en/master/latex.html?highlight=pdf

latex_engine = "xelatex"
latex_documents = [("index", "glm.tex", "广义线性模型", "张振虎", "manual", True), ]
# If given, this must be the name of an image file (relative to the configuration directory)
# that is the logo of the docs. It is placed at the top of the title page. Default: None.
latex_logo = None
#  'part' , 'chapter' or 'section'
latex_toplevel_sectioning = 'chapter'

# A list of document names to append as an appendix to all manuals.
latex_appendices = []

# 控制着 生成最后的索引
latex_domain_indices = False

# If true, add page references after internal references.
# This is very useful for printed copies of the manual. Default is False.
latex_show_pagerefs = True

# If false, no module index is generated.
latex_domain_indices = False

# -- Options for math -------------------------------------------------

math_number_all = True
math_eqref_format = "公式({number})"

numfig = True
numfig_secnum_depth = (2)

# 一个支持定义、定理、证明指令的扩展插件
# define theorems in LaTeX, using the starred command (provided by amsthm or ntheorem):
# https://sphinxcontrib-proof.readthedocs.io/en/latest/faq/#numbered-theorems
latex_elements = {
    #     # Additional stuff for the LaTeX preamble.
    #     "preamble": r"""
    #        \usepackage{amsthm}
    #
    #        \newtheorem*{definition}{Definition}
    #        \newtheorem*{theorem}{Theorem}
    #     """,
    "releasename": "张振虎",
}
